/**
 * Банк задания №8: десять зафиксированных вариантов на прототип.
 *
 * Файл собирается скриптом scripts/build-bank-8.mjs и правится
 * только им: скрипт перебирает seed по порядку и берёт первые
 * десять, у которых условия разные, ответы не повторяются чаще трёх
 * раз и уровни распределены 6:4. Самотест проверяет то же самое.
 */

import type { Level } from './types';

export interface BankVariant {
  /** Номер варианта: 1…10. */
  n: number;
  seed: string;
  level: Level | null;
}

export interface BankEntry {
  prototype: string;
  variants: BankVariant[];
}

export const BANK: BankEntry[] = [
  {
    prototype: '8.A',
    variants: [
      { n: 1, seed: '8.A#1', level: 'base' },
      { n: 2, seed: '8.A#2', level: 'advanced' },
      { n: 3, seed: '8.A#3', level: 'base' },
      { n: 4, seed: '8.A#4', level: 'base' },
      { n: 5, seed: '8.A#5', level: 'advanced' },
      { n: 6, seed: '8.A#6', level: 'base' },
      { n: 7, seed: '8.A#7', level: 'advanced' },
      { n: 8, seed: '8.A#8', level: 'base' },
      { n: 9, seed: '8.A#9', level: 'base' },
      { n: 10, seed: '8.A#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.B',
    variants: [
      { n: 1, seed: '8.B#1', level: 'base' },
      { n: 2, seed: '8.B#2', level: 'advanced' },
      { n: 3, seed: '8.B#3', level: 'base' },
      { n: 4, seed: '8.B#4', level: 'base' },
      { n: 5, seed: '8.B#5', level: 'advanced' },
      { n: 6, seed: '8.B#6', level: 'base' },
      { n: 7, seed: '8.B#7', level: 'advanced' },
      { n: 8, seed: '8.B#8', level: 'base' },
      { n: 9, seed: '8.B#9', level: 'base' },
      { n: 10, seed: '8.B#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.C',
    variants: [
      { n: 1, seed: '8.C#1', level: 'base' },
      { n: 2, seed: '8.C#2', level: 'advanced' },
      { n: 3, seed: '8.C#3', level: 'base' },
      { n: 4, seed: '8.C#4', level: 'base' },
      { n: 5, seed: '8.C#5', level: 'advanced' },
      { n: 6, seed: '8.C#6', level: 'base' },
      { n: 7, seed: '8.C#7', level: 'advanced' },
      { n: 8, seed: '8.C#8', level: 'base' },
      { n: 9, seed: '8.C#9', level: 'base' },
      { n: 10, seed: '8.C#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.D',
    variants: [
      { n: 1, seed: '8.D#1', level: 'base' },
      { n: 2, seed: '8.D#2', level: 'advanced' },
      { n: 3, seed: '8.D#3', level: 'base' },
      { n: 4, seed: '8.D#4', level: 'base' },
      { n: 5, seed: '8.D#5', level: 'advanced' },
      { n: 6, seed: '8.D#9', level: 'base' },
      { n: 7, seed: '8.D#10', level: 'advanced' },
      { n: 8, seed: '8.D#12', level: 'base' },
      { n: 9, seed: '8.D#14', level: 'base' },
      { n: 10, seed: '8.D#15', level: 'advanced' },
    ],
  },
  {
    prototype: '8.E',
    variants: [
      { n: 1, seed: '8.E#1', level: 'base' },
      { n: 2, seed: '8.E#2', level: 'advanced' },
      { n: 3, seed: '8.E#3', level: 'base' },
      { n: 4, seed: '8.E#4', level: 'base' },
      { n: 5, seed: '8.E#5', level: 'advanced' },
      { n: 6, seed: '8.E#6', level: 'base' },
      { n: 7, seed: '8.E#7', level: 'advanced' },
      { n: 8, seed: '8.E#8', level: 'base' },
      { n: 9, seed: '8.E#9', level: 'base' },
      { n: 10, seed: '8.E#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.F',
    variants: [
      { n: 1, seed: '8.F#1', level: null },
      { n: 2, seed: '8.F#2', level: null },
      { n: 3, seed: '8.F#3', level: null },
      { n: 4, seed: '8.F#4', level: null },
      { n: 5, seed: '8.F#5', level: null },
      { n: 6, seed: '8.F#6', level: null },
      { n: 7, seed: '8.F#7', level: null },
      { n: 8, seed: '8.F#8', level: null },
      { n: 9, seed: '8.F#9', level: null },
      { n: 10, seed: '8.F#10', level: null },
    ],
  },
  {
    prototype: '8.G',
    variants: [
      { n: 1, seed: '8.G#1', level: null },
      { n: 2, seed: '8.G#2', level: null },
      { n: 3, seed: '8.G#3', level: null },
      { n: 4, seed: '8.G#4', level: null },
      { n: 5, seed: '8.G#5', level: null },
      { n: 6, seed: '8.G#6', level: null },
      { n: 7, seed: '8.G#7', level: null },
      { n: 8, seed: '8.G#8', level: null },
      { n: 9, seed: '8.G#10', level: null },
      { n: 10, seed: '8.G#12', level: null },
    ],
  },
  {
    prototype: '8.H',
    variants: [
      { n: 1, seed: '8.H#1', level: 'base' },
      { n: 2, seed: '8.H#2', level: 'advanced' },
      { n: 3, seed: '8.H#3', level: 'base' },
      { n: 4, seed: '8.H#4', level: 'base' },
      { n: 5, seed: '8.H#5', level: 'advanced' },
      { n: 6, seed: '8.H#6', level: 'base' },
      { n: 7, seed: '8.H#7', level: 'advanced' },
      { n: 8, seed: '8.H#9', level: 'base' },
      { n: 9, seed: '8.H#10', level: 'base' },
      { n: 10, seed: '8.H#11', level: 'advanced' },
    ],
  },
  {
    prototype: '8.I',
    variants: [
      { n: 1, seed: '8.I#1', level: null },
      { n: 2, seed: '8.I#2', level: null },
      { n: 3, seed: '8.I#3', level: null },
      { n: 4, seed: '8.I#4', level: null },
      { n: 5, seed: '8.I#6', level: null },
      { n: 6, seed: '8.I#7', level: null },
      { n: 7, seed: '8.I#8', level: null },
      { n: 8, seed: '8.I#11', level: null },
      { n: 9, seed: '8.I#14', level: null },
      { n: 10, seed: '8.I#18', level: null },
    ],
  },
  {
    prototype: '8.J',
    variants: [
      { n: 1, seed: '8.J#1', level: 'base' },
      { n: 2, seed: '8.J#2', level: 'advanced' },
      { n: 3, seed: '8.J#3', level: 'base' },
      { n: 4, seed: '8.J#4', level: 'base' },
      { n: 5, seed: '8.J#5', level: 'advanced' },
      { n: 6, seed: '8.J#6', level: 'base' },
      { n: 7, seed: '8.J#7', level: 'advanced' },
      { n: 8, seed: '8.J#8', level: 'base' },
      { n: 9, seed: '8.J#10', level: 'base' },
      { n: 10, seed: '8.J#12', level: 'advanced' },
    ],
  },
  {
    prototype: '8.K',
    variants: [
      { n: 1, seed: '8.K#1', level: 'base' },
      { n: 2, seed: '8.K#2', level: 'advanced' },
      { n: 3, seed: '8.K#3', level: 'base' },
      { n: 4, seed: '8.K#4', level: 'base' },
      { n: 5, seed: '8.K#6', level: 'advanced' },
      { n: 6, seed: '8.K#7', level: 'base' },
      { n: 7, seed: '8.K#8', level: 'advanced' },
      { n: 8, seed: '8.K#10', level: 'base' },
      { n: 9, seed: '8.K#11', level: 'base' },
      { n: 10, seed: '8.K#12', level: 'advanced' },
    ],
  },
  {
    prototype: '8.L',
    variants: [
      { n: 1, seed: '8.L#1', level: 'base' },
      { n: 2, seed: '8.L#2', level: 'advanced' },
      { n: 3, seed: '8.L#3', level: 'base' },
      { n: 4, seed: '8.L#4', level: 'base' },
      { n: 5, seed: '8.L#5', level: 'advanced' },
      { n: 6, seed: '8.L#7', level: 'base' },
      { n: 7, seed: '8.L#8', level: 'advanced' },
      { n: 8, seed: '8.L#10', level: 'base' },
      { n: 9, seed: '8.L#11', level: 'base' },
      { n: 10, seed: '8.L#12', level: 'advanced' },
    ],
  },
  {
    prototype: '8.M',
    variants: [
      { n: 1, seed: '8.M#1', level: 'base' },
      { n: 2, seed: '8.M#2', level: 'advanced' },
      { n: 3, seed: '8.M#3', level: 'base' },
      { n: 4, seed: '8.M#4', level: 'base' },
      { n: 5, seed: '8.M#5', level: 'advanced' },
      { n: 6, seed: '8.M#6', level: 'base' },
      { n: 7, seed: '8.M#7', level: 'advanced' },
      { n: 8, seed: '8.M#8', level: 'base' },
      { n: 9, seed: '8.M#9', level: 'base' },
      { n: 10, seed: '8.M#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.N',
    variants: [
      { n: 1, seed: '8.N#1', level: 'base' },
      { n: 2, seed: '8.N#2', level: 'advanced' },
      { n: 3, seed: '8.N#3', level: 'base' },
      { n: 4, seed: '8.N#4', level: 'base' },
      { n: 5, seed: '8.N#5', level: 'advanced' },
      { n: 6, seed: '8.N#6', level: 'base' },
      { n: 7, seed: '8.N#7', level: 'advanced' },
      { n: 8, seed: '8.N#10', level: 'base' },
      { n: 9, seed: '8.N#11', level: 'base' },
      { n: 10, seed: '8.N#13', level: 'advanced' },
    ],
  },
  {
    prototype: '8.O',
    variants: [
      { n: 1, seed: '8.O#1', level: 'base' },
      { n: 2, seed: '8.O#2', level: 'advanced' },
      { n: 3, seed: '8.O#3', level: 'base' },
      { n: 4, seed: '8.O#4', level: 'base' },
      { n: 5, seed: '8.O#5', level: 'advanced' },
      { n: 6, seed: '8.O#6', level: 'base' },
      { n: 7, seed: '8.O#7', level: 'advanced' },
      { n: 8, seed: '8.O#8', level: 'base' },
      { n: 9, seed: '8.O#11', level: 'base' },
      { n: 10, seed: '8.O#12', level: 'advanced' },
    ],
  },
  {
    prototype: '8.P',
    variants: [
      { n: 1, seed: '8.P#1', level: 'base' },
      { n: 2, seed: '8.P#2', level: 'advanced' },
      { n: 3, seed: '8.P#3', level: 'base' },
      { n: 4, seed: '8.P#4', level: 'base' },
      { n: 5, seed: '8.P#5', level: 'advanced' },
      { n: 6, seed: '8.P#6', level: 'base' },
      { n: 7, seed: '8.P#7', level: 'advanced' },
      { n: 8, seed: '8.P#9', level: 'base' },
      { n: 9, seed: '8.P#10', level: 'base' },
      { n: 10, seed: '8.P#11', level: 'advanced' },
    ],
  },
  {
    prototype: '8.Q',
    variants: [
      { n: 1, seed: '8.Q#1', level: 'base' },
      { n: 2, seed: '8.Q#2', level: 'advanced' },
      { n: 3, seed: '8.Q#3', level: 'base' },
      { n: 4, seed: '8.Q#4', level: 'base' },
      { n: 5, seed: '8.Q#5', level: 'advanced' },
      { n: 6, seed: '8.Q#6', level: 'base' },
      { n: 7, seed: '8.Q#7', level: 'advanced' },
      { n: 8, seed: '8.Q#8', level: 'base' },
      { n: 9, seed: '8.Q#9', level: 'base' },
      { n: 10, seed: '8.Q#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.R',
    variants: [
      { n: 1, seed: '8.R#1', level: 'base' },
      { n: 2, seed: '8.R#2', level: 'advanced' },
      { n: 3, seed: '8.R#3', level: 'base' },
      { n: 4, seed: '8.R#4', level: 'base' },
      { n: 5, seed: '8.R#5', level: 'advanced' },
      { n: 6, seed: '8.R#6', level: 'base' },
      { n: 7, seed: '8.R#7', level: 'advanced' },
      { n: 8, seed: '8.R#8', level: 'base' },
      { n: 9, seed: '8.R#9', level: 'base' },
      { n: 10, seed: '8.R#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.S',
    variants: [
      { n: 1, seed: '8.S#1', level: 'base' },
      { n: 2, seed: '8.S#2', level: 'advanced' },
      { n: 3, seed: '8.S#3', level: 'base' },
      { n: 4, seed: '8.S#4', level: 'base' },
      { n: 5, seed: '8.S#5', level: 'advanced' },
      { n: 6, seed: '8.S#6', level: 'base' },
      { n: 7, seed: '8.S#7', level: 'advanced' },
      { n: 8, seed: '8.S#8', level: 'base' },
      { n: 9, seed: '8.S#9', level: 'base' },
      { n: 10, seed: '8.S#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.T',
    variants: [
      { n: 1, seed: '8.T#1', level: 'base' },
      { n: 2, seed: '8.T#2', level: 'advanced' },
      { n: 3, seed: '8.T#3', level: 'base' },
      { n: 4, seed: '8.T#4', level: 'base' },
      { n: 5, seed: '8.T#5', level: 'advanced' },
      { n: 6, seed: '8.T#6', level: 'base' },
      { n: 7, seed: '8.T#7', level: 'advanced' },
      { n: 8, seed: '8.T#8', level: 'base' },
      { n: 9, seed: '8.T#9', level: 'base' },
      { n: 10, seed: '8.T#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.U',
    variants: [
      { n: 1, seed: '8.U#1', level: 'base' },
      { n: 2, seed: '8.U#2', level: 'advanced' },
      { n: 3, seed: '8.U#3', level: 'base' },
      { n: 4, seed: '8.U#4', level: 'base' },
      { n: 5, seed: '8.U#5', level: 'advanced' },
      { n: 6, seed: '8.U#6', level: 'base' },
      { n: 7, seed: '8.U#7', level: 'advanced' },
      { n: 8, seed: '8.U#8', level: 'base' },
      { n: 9, seed: '8.U#9', level: 'base' },
      { n: 10, seed: '8.U#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.V',
    variants: [
      { n: 1, seed: '8.V#1', level: 'base' },
      { n: 2, seed: '8.V#2', level: 'advanced' },
      { n: 3, seed: '8.V#3', level: 'base' },
      { n: 4, seed: '8.V#4', level: 'base' },
      { n: 5, seed: '8.V#5', level: 'advanced' },
      { n: 6, seed: '8.V#6', level: 'base' },
      { n: 7, seed: '8.V#7', level: 'advanced' },
      { n: 8, seed: '8.V#8', level: 'base' },
      { n: 9, seed: '8.V#9', level: 'base' },
      { n: 10, seed: '8.V#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.W',
    variants: [
      { n: 1, seed: '8.W#1', level: 'base' },
      { n: 2, seed: '8.W#2', level: 'advanced' },
      { n: 3, seed: '8.W#3', level: 'base' },
      { n: 4, seed: '8.W#4', level: 'base' },
      { n: 5, seed: '8.W#5', level: 'advanced' },
      { n: 6, seed: '8.W#6', level: 'base' },
      { n: 7, seed: '8.W#7', level: 'advanced' },
      { n: 8, seed: '8.W#8', level: 'base' },
      { n: 9, seed: '8.W#9', level: 'base' },
      { n: 10, seed: '8.W#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.X',
    variants: [
      { n: 1, seed: '8.X#1', level: 'base' },
      { n: 2, seed: '8.X#2', level: 'advanced' },
      { n: 3, seed: '8.X#3', level: 'base' },
      { n: 4, seed: '8.X#4', level: 'base' },
      { n: 5, seed: '8.X#5', level: 'advanced' },
      { n: 6, seed: '8.X#6', level: 'base' },
      { n: 7, seed: '8.X#7', level: 'advanced' },
      { n: 8, seed: '8.X#8', level: 'base' },
      { n: 9, seed: '8.X#9', level: 'base' },
      { n: 10, seed: '8.X#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.Y',
    variants: [
      { n: 1, seed: '8.Y#1', level: 'base' },
      { n: 2, seed: '8.Y#2', level: 'advanced' },
      { n: 3, seed: '8.Y#3', level: 'base' },
      { n: 4, seed: '8.Y#4', level: 'base' },
      { n: 5, seed: '8.Y#5', level: 'advanced' },
      { n: 6, seed: '8.Y#6', level: 'base' },
      { n: 7, seed: '8.Y#7', level: 'advanced' },
      { n: 8, seed: '8.Y#8', level: 'base' },
      { n: 9, seed: '8.Y#9', level: 'base' },
      { n: 10, seed: '8.Y#10', level: 'advanced' },
    ],
  },
  {
    prototype: '8.Z',
    variants: [
      { n: 1, seed: '8.Z#1', level: 'base' },
      { n: 2, seed: '8.Z#2', level: 'advanced' },
      { n: 3, seed: '8.Z#3', level: 'base' },
      { n: 4, seed: '8.Z#4', level: 'base' },
      { n: 5, seed: '8.Z#5', level: 'advanced' },
      { n: 6, seed: '8.Z#6', level: 'base' },
      { n: 7, seed: '8.Z#7', level: 'advanced' },
      { n: 8, seed: '8.Z#9', level: 'base' },
      { n: 9, seed: '8.Z#10', level: 'base' },
      { n: 10, seed: '8.Z#11', level: 'advanced' },
    ],
  },
];
